version: '3.8'

services:
  scrapper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapper
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - LOG_LEVEL=info
      - BROWSER_TYPE=firefox
      - BROWSER_CONTEXT_LIMIT=20
      - SCREENSHOT_TYPE=jpeg
      - SCREENSHOT_QUALITY=80
      - UVICORN_WORKERS=5
      - DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/misc/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for enhanced caching (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   container_name: scrapper-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data: