version: '3.8'

services:
  scrapper:
    image: amerkurev/scrapper
    container_name: web-scrapper
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=error
      - BROWSER_TYPE=firefox
      - SCREENSHOT_TYPE=jpeg
      - SCREENSHOT_QUALITY=90
      - UVICORN_WORKERS=4
      - DEBUG=false